# Generated by Django 5.0 on 2023-12-22 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institute', verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='group',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departament', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupcourse', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='course_stage',
            field=models.IntegerField(verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
