# Generated by Django 5.0 on 2023-12-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_can_post_event',
            field=models.BooleanField(default=False, verbose_name='Может создавать мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
    ]
