# Generated by Django 5.0 on 2023-12-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_role_is_can_post_event_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Фото'),
        ),
    ]
