# Generated by Django 5.0 on 2023-12-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='addres',
            field=models.CharField(default='Таганрог, ул. Чехова, д1', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcategory'),
        ),
    ]
