# Generated by Django 5.0 on 2023-12-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_event_latitude_remove_event_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='addres',
            new_name='address',
        ),
    ]
