# Generated by Django 5.0 on 2023-12-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_addres_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='color_hex',
            field=models.CharField(default='#050505', max_length=10, verbose_name='HEX цвета'),
            preserve_default=False,
        ),
    ]
