# Generated by Django 5.0 on 2023-12-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_eventcategory_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetime_of_event',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конца'),
        ),
        migrations.AddField(
            model_name='event',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
    ]
